# Default values for 01_httpd_basic_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
labels:
  app: frontend
  org: insurance

image:
  repository: httpd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.4.56"

serviceAccount:
  create: true
  name: my-sa